name: "Setup"
description: Setup action

runs:
  using: "composite"
  steps:
    - name: Use nodejs
      uses: actions/setup-node@v3
      with:
        node-version: 16.18

    - name: restore workspace cache
      uses: actions/cache@v3
      id: node_modules
      with:
        path: |
          node_modules
          packages/*/node_modules
        key: node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-${{ hashFiles('yarn.lock', 'patches/*.patch') }}
        restore-keys: |
          node-modules-v2-${{ runner.os }}-${{ steps.node-version.outputs.version }}-

    - run: yarn install --frozen-lockfile --network-timeout 9000000
      if: steps.node_modules.outputs.cache-hit != 'true'
      shell: bash
