name: "Build Cache"
description: build cache

runs:
  using: "composite"
  steps:
    - name: build cache
      uses: actions/cache@v3
      with:
        path: |
          node_modules
          packages/*/dist
          packages/*/es
          packages/jimp/browser/lib
        key: ${{ github.run_id }}
        restore-keys: ${{ github.run_id }}
